### ISSUE TITLE
`paver develop_link` fails if `.pio_envs` directory does not exist in root of repository

### ISSUE THREAD

**Issue by cfobel** [wheeler-microfluidics/platformio-helpers#2]
If `.pio_envs` directory does not exist in root of repository before calling `paver develop_link`, the following error occurs:

```python
Traceback (most recent call last):
  File "C:\Users\chris\Miniconda2\envs\rpc-project\lib\site-packages\paver\tasks.py", line 196, in _run_task
    return do_task()
  File "C:\Users\chris\Miniconda2\envs\rpc-project\lib\site-packages\paver\tasks.py", line 193, in do_task
    return func(**kw)
  File "pavement.py", line 71, in develop_link
    package_name=package_name)
  File "C:\Users\chris\Miniconda2\envs\rpc-project\lib\site-packages\platformio_helpers\develop.py", line 66, in link
    working_dir.joinpath('.pioenvs').junction(fw_bin_dir)
  File "C:\Users\chris\Miniconda2\envs\rpc-project\lib\site-packages\ntfsutils\junction.py", line 116, in create
    raise Exception("%s is not a directory" % source)
Exception: C:\Users\chris\Documents\GitHub\rpc-project-template\.pioenvs is not a directory
```

Workaround
--------------

Manually create `.pioenvs` directory in root of working repository and call `paver develop_link` again.

Proposed solution
--------------------

Add check in `platformio_helpers/develop.py:link` to create `.pioenvs` directory if it doesn't exist before performing link operation.

**Comment by cfobel** [comment]
Fixed in [release `v0.3.2`][1].

[1]: https://github.com/wheeler-microfluidics/platformio-helpers/releases/tag/v0.3.2
